### ISSUE TITLE
Create Route List

### ISSUE THREAD

**Issue by rizabach29** [agustinanisaf/SquareCheck-backend#27]
Membuat list dari route berdasarkan [Link Dokumentasi API Square Check](https://documenter.getpostman.com/view/8289361/TVRn47ch)

- [x] User

- [x] Token

- [x] Login

- [x] Student

- [x] Lecturer

- [x] Department

- [x] Schedule

- [x] Subject

- [x] Academic Calendar

- [x] Academic Calendar Type

**Comment by rizabach29** [comment]
aku uda buat resource e

**Comment by ryuuzake** [comment]
push en seh beberapa bach sing wes bok up, tak ngikut iku @rizabach29

**Comment by rizabach29** [comment]
okeokee @ryuuzake, beberapa tok tapi

**Comment by rizabach29** [comment]
@ryuuzake tulung gantino nama route e calendar, aku sek pake camelcase
