### ISSUE TITLE
Create Kalender Akademik Migration

### ISSUE THREAD

**Issue by ryuuzake** [agustinanisaf/SquareCheck-backend#5]
Tolong bikinkan Migrationnya sesuai dengan [design ini](https://dbdiagram.io/d/5f7d30bd3a78976d7b76a0d5)

Kalau ada kendala atau hal yang dibingungkan bisa dicomment di issues ini aja biar jadi satu dan kalau mentor nimbrung bisa langsung comment juga

**Comment by macbookfilip** [comment]
Hi, could you tell me something more about this issue please?
